[workspace]
resolver = "3"
members = [
    "2018",
    "2025/day10",
    "2025/day3",
    "2025/day4",
    "2025/day5",
    "2025/day6",
    "2025/day7",
    "2025/day8",
    "2025/day9"
, "aoc-utils"]
