[package]
name = "advent-of-code-2018"
version = "0.1.0"
authors = ["Jim Blandy <jimb@red-bean.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
itertools = "0.8.0"
lazy_static = "1.2.0"

[dependencies.aoc-utils]
path = "../aoc-utils"
