[package]
name = "day9"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
binary-heap-plus = "0.5"
compare = "0.1"
env_logger = "0.11"
log = "0.4"

[dependencies.image]
version = "0.25.9"
default-features = false
features = ["png", "rayon"]
